spring:
  application:
    name: AuthService
  datasource:
    url: jdbc:postgresql://localhost:5432/auth_db
    username: postgres
    password: password
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    show-sql: true
  liquibase:
    change-log: classpath:db/changelog/changelog-master.xml

server:
  port: 8081

customer:
  service:
    url: ${CUSTOMER_SERVICE_URL:http://localhost:8082}

jwt:
  secret: ${JWT_SECRET:HMHHFu9OkiscolD1SI+H7Ae5aBwJiw8vyMfcFkZOtYFI4mljUvsHONlsRFlVsYjYg1MlndmrYyJb5aYT/aq1NQ==}

admin:
  registration:
    token: HMHHFu9OkiscolD1SI+H7Ae5aBwJiw8vyMfcFkZOtYFI4mljUvsHONlsRFlVsYjYg1MlndmrY

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
    register-with-eureka: true
    fetch-registry: true
  instance:
    preferIpAddress: true      # tell Eureka to publish an IP, not the host name
    ip-address: host.docker.internal       # works locally; change if you run in Docker/VPS
    instance-id: ${spring.application.name}:${server.port}
